### ISSUE TITLE
Support for BSD platforms?

### ISSUE THREAD

**Issue by cfallin** [bytecodealliance/posish#11]
Greetings! One of my occasional hobby activities is to try to compile `wasmtime` on unsupported platforms. I managed to get it to work last October on OpenBSD ([branch](https://github.com/cfallin/wasmtime/tree/openbsd)) with a number of hacks in the platform code. I thought I would get back to this and try with the latest `main` this morning, and saw a number of build errors in `posish`, which seems to be the new platform glue we use -- a representative example:

```
error[E0432]: unresolved import `libc::posix_fadvise`                                                                                                
 --> /home/cfallin/.cargo/registry/src/github.com-1ecc6299db9ec823/posish-0.6.1/src/fs/fadvise.rs:8:5                                                
  |                                                                                                                                                  
8 | use libc::posix_fadvise as libc_posix_fadvise;                                                                                                   
  |     ^^^^^^-------------^^^^^^^^^^^^^^^^^^^^^^                                                                                                    
  |     |     |                                                                                                                                      
  |     |     help: a similar name exists in the module: `posix_madvise`                                                                             
  |     no `posix_fadvise` in the root          
```

and a bunch more related to `fadvise`, `posix_fallocate`, `makedev`, `CLOCK_PROCESS_CPUTIME_ID`, etc. (OpenBSD seems not to have the first two at all; and last time I tried this I had to rip out some of the process cpu-time stuff too.)

This is somewhat unsurprising, given that low-level details like this will undoubtedly (i) be missing on some platforms, or (ii) at least not be implemented in the right places in lower-level crates like `libc`, and BSD platforms are much more niche.

That said, I am curious: are there plans at any point to try to build/run on BSD systems, even at a best-effort ("fallocate is stubbed out with `unimplemented!("system does not support this syscall")`") level?

Take this as a feature request at the lowest-possible priority; it would be neat to be able to run Wasm on my little OpenBSD router, and various other folks might be using one of the BSDs in their infrastructure, but it's far from critical :-)

**Comment by sunfishcode** [comment]
posish, through being depended on by cap-std, is regularly tested on FreeBSD and regularly `cargo check`'d for NetBSD, so OpenBSD support is probably feasible. I expect most of the work is just adding `target_os = "openbsd"` in places that already have `target_os = "freebsd"` and/or `target_os = "netbsd"`.

**Comment by sunfishcode** [comment]
Also, `fadvse` can be implemented as a no-op, since it's just an optimization hint. And `posix_fallocate` can be `unimplemented!` since it's relatively uncommon and the associated WASI functions are likely to be removed anyway in the future due to not being fully implementable on Windows or macOS. I'm not actively working on porting this to OpenBSD myself, but I'm happy to help anyone interested.

**Comment by sunfishcode** [comment]
This is now fixed!
