### ISSUE TITLE
no_std possible?

### ISSUE THREAD

**Issue by pmmccorm** [bytecodealliance/posish#17]
I am new to Rust and just took a peek at the source.

Would it be possible to make the `linux_raw` backend no_std? Or have a no_std backend?

I am looking for something just like posish: higher level than syscalls-rs, but I don't want to manually human-ize all the syscalls (and half of them are not even needed).

**Comment by sunfishcode** [comment]
It might be. I expect it'd be straightforward to put [conversion from `posish::io::Error` to `std::io::Error`](https://github.com/bytecodealliance/posish/blob/main/src/io/error.rs#L58), [`OsString` argument support](https://github.com/bytecodealliance/posish/blob/main/src/path/arg.rs#L287), and similar things behind a `#[not(feature = "std")]`. One would also need to find `no_std` replacements for at least [`std::os::raw`](https://doc.rust-lang.org/stable/std/os/raw/index.html), [`CStr`](https://doc.rust-lang.org/stable/std/ffi/struct.CStr.html), [`CString`](https://doc.rust-lang.org/stable/std/ffi/struct.CString.html), which posish uses a lot.

**Comment by sunfishcode** [comment]
Can you say more about why you need `no_std` support? `posish` is all about making syscalls, which essentially requires the existence of an OS or OS-like entity, so it's not immediately clear that it makes sense to be `no_std`.

**Comment by pmmccorm** [comment]
Yes of course: I am working on a written-in-rust C library. I don't want to link against libc, and I just need a few syscalls.

EG: I am implementing `libm.so` (and lets say libm.so actually does a few syscalls). I want to produce a libm.so from rust source that is not linked with any external libraries (except vdso) and that can be LD_PRELOADED as a replacement.

It might be a unique requirement, but for Linux at least syscalls remain stable (so the libc abstraction over them is not needed), and the way you are doing it is to pick handfuls of modern and useful ones and rust-ify those so it is a nice interface to work with vs other syscall crates that are just thin wrappers around the ASM.

**Comment by sunfishcode** [comment]
Would you mind saying more about why you need `no_std` for this? It's common for C libraries to depend on libc.so; even libm.so does on common platforms.

This is a space where there are a number of different options which all come with complex tradeoffs, so it can be very useful to dig down to the bottom of "why do I really need this?".

**Comment by pmmccorm** [comment]
In the context of the original thread: it would be nice to have a "pure" rust runtime that does not depend on libc.

This gave me the idea to try this with a smaller subset of libc: `pthreads.so` or `libm.so`.

These could be created piece-meal and and offer "legacy" C-APIs without requiring all of libc. EG I want to compile against my rust-pthread implementation:

```
gcc -lrthreads.so ./pthread_program.c

or

LD_PRELOAD=rthreads.so ./pthread_program
```

So is that worth the tradeoff for posish? I don't know, but I ask because it seems like it is engineered to be able to implement this (relatively) easily: you have the concept of different syscall backends, offer high level rust interfaces abstracting over them, and use a minimal set of types from std.

When I was playing around with this myself I came across syscall crates that all did something like:
1) raw assembly syscalls: these are no std, but the interface is of course miserable: `syscall_4_arg(NR15, arg1, arg2, ...)
2) just wrappers over glibc's syscall(), which is a more simple implementation but now requires libc crate

When what I really wanted was 1 with a rust interface over the top..basically a no_std crate / `libsyscall.so`.

**Comment by sunfishcode** [comment]
Thanks!

> In the context of the original thread: it would be nice to have a "pure" rust runtime that does not depend on libc.

One way we could imagine doing this would be to propose putting (parts of) (a hypothetical future version of) posish into std itself, replacing direct calls to libc. If we did that, the code wouldn't need to be `no_std`; it could just use std. As such, I'm a little hesitant to take on the extra work of finding and replacing the parts of std that we use (CStr, CString, std::os::raw:*, etc.) and complicating the codebase until we have a clearer sense of which path we want to take. Or a clear use case that needs no_std.

> This gave me the idea to try this with a smaller subset of libc: `pthreads.so` or `libm.so`.
> 
> These could be created piece-meal and and offer "legacy" C-APIs without requiring all of libc. EG I want to compile against my rust-pthread implementation:
> 
> ```
> gcc -lrthreads.so ./pthread_program.c
> 
> or
> 
> LD_PRELOAD=rthreads.so ./pthread_program
> ```

In this example, I assume `pthread_program` depends on libc anyway, so I imagine it's fine for libpthread to depend on libc as well.

As an aside, libpthread implementations often have special relationships with their associated libc implementations, using private symbols and such, so I'd advise caution if attempting libpthread.

**Comment by pmmccorm** [comment]
OK. Had to ask.

**Comment by sunfishcode** [comment]
As of https://github.com/bytecodealliance/posish/pull/24 and https://github.com/bytecodealliance/posish/pull/26, posish doesn't use anything in std which makes syscalls. As a result, the path to no_std should be straightforward in theory.

**Comment by pmmccorm** [comment]
I'll play around with it. Thanks!

**Comment by sunfishcode** [comment]
I recently did more of a survey of our use of `std`; not counting things in `core` or `alloc`. The results may be of interest here:
 - `std::os::raw::c_*`: C types
 - `std::ffi::CStr`/`CString`/`OsStr`/`OsString`
 - `std::path::Path`/`PathBuf` - but not the parts that are aliases for `std::fs` functions
 - `std::io::SeekFrom`
 - `std::io::Error`, but only to define convenience conversions to and from `rsix::io::Error`
 - `std::io::IoSlice`/`IoSliceMut`: vectored I/O types
 - `std::net::Ipv4Addr`/`Ipv6Addr`/`SocketAddrV4`/`SocketAddrV6`
 - `std::os::*::io::RawFd`/`AsRawFd`/etc.

**Comment by sunfishcode** [comment]
I now have a branch of `rsix` which is ported to `no_std`: https://github.com/bytecodealliance/rsix/tree/no_std_demo

This demonstrates that it can be done, and it shows what kinds of polyfills are needed. My sense right now is to leave this as a branch, which may be occasionally updated and isn't a burden to day-to-day development, but I'm open to considering other options if there are compelling use cases.

**Comment by pmmccorm** [comment]
Very cool. I will look at this. I have been on a break.

**Comment by pmmccorm** [comment]
It is at least interesting to be aware of the gap between std and no_std. At least for me anyways.
